name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download Go modules
        run: go mod download
      
      - name: Generate grpc and sqcl files
        run: task generate

      - name: Test
        run: task test

      - name: Build
        run: task build:app

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            pkg/auth_v1/
            internal/auth/
          retention-days: 1
  push-image:
    needs: test-and-build
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - name: Download generated code
        uses: actions/download-artifact@v7
        with: 
          name: generated-files
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=prod,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: [test-and-build, push-image]
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "docker-compose.yml,docker-compose.prod.yml,Taskfile.yml"
            target: "/home/${{ secrets.REMOTE_USER }}/auth"

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GOOSE_DBSTRING,GOOSE_DRIVER,PORT,DOCKER_TAG
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/auth
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "GOOSE_DBSTRING=\"$GOOSE_DBSTRING\"" > .env.prod
            echo "GOOSE_DRIVER=$GOOSE_DRIVER" >> .env.prod
            echo "PORT=$PORT" >> .env.prod
            export DOCKER_TAG=${DOCKER_TAG}
            ENV=prod task docker:prod:up
            docker logout
        env:
          GOOSE_DBSTRING: ${{ secrets.GOOSE_DBSTRING }}
          GOOSE_DRIVER: ${{ secrets.GOOSE_DRIVER }}
          PORT: ${{ secrets.PORT }}
          DOCKER_TAG: ${{ needs.push-image.outputs.image_tag }}